----------------------------- EXEUCUTIVE SUMMARY (BUSINESS KPIs) -------------------------

-- What is the total revenue generated by the pizza store?
SELECT ROUND(SUM(pizzas.price * order_details.quantity),2) AS Total_Revenue FROM pizzas JOIN order_details
ON pizzas.pizza_id = order_details.pizza_id;


-- How many total orders were placed during the analysis period?
SELECT COUNT(DISTINCT order_id) AS Total_Orders FROM orders;


-- How many pizzas were sold in total?
SELECT SUM(quantity) AS Total_QTY_Sold FROM order_details;


-- What is the average order value (AOV) of customers?
SELECT ROUND(SUM(pizzas.price * order_details.quantity)  / COUNT(DISTINCT order_details.order_id), 2) AS Average_Order_Value
FROM pizzas JOIN order_details
ON pizzas.pizza_id = order_details.pizza_id;


-- Which pizza categories generate the highest revenue?
SELECT pizza_types.category, ROUND(SUM(pizzas.price * order_details.quantity),2) AS Total_Revenue FROM pizzas JOIN order_details
ON pizzas.pizza_id = order_details.pizza_id JOIN pizza_types
ON pizza_types.pizza_type_id = pizzas.pizza_type_id
GROUP BY pizza_types.category
ORDER BY Total_Revenue DESC;
